version: '3.8'

services:
  app:
    image: gmjsilmaro/pixelcare:staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./sessions:/app/sessions
    restart: unless-stopped
