version: '3.8'

services:
  app:
    image: gmjsilmaro/pixelcare:${VERSION:-1.0.0}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VERSION=${VERSION:-1.0.0}
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./sessions:/app/sessions
    restart: always
